# Generated by Django 3.0.7 on 2020-06-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scripttag',
            old_name='scr',
            new_name='scr_link',
        ),
    ]
