# Generated by Django 3.0.7 on 2020-06-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_auto_20200609_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptTag',
        ),
    ]
